version: "3.3"

services:

  prometheus:
    
    image: ubuntu/prometheus
    container_name: prometheus
    
    ports:
      - 9090:9090

    volumes:
      - ./prometheus:/etc/prometheus
    
  grafana:

    image: grafana/grafana
    container_name: grafana

    ports:
      - 3000:3000
    
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
